/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.LoginHistory;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author lnt09
 */
public class LoginHistory extends javax.swing.JPanel {

    /**
     * Creates new form LoginHistory
     */
    public LoginHistory() {
        initComponents();
        setOpaque(false);
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});
        loginHistoryTable.addRow(new Object[]{"2003/12/02", "Roseanna Antczak", "Apt 1559"});

        // Thiết lập renderer cho cột 1 (index 0) là căn lề trái
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        loginHistoryTable.getColumnModel().getColumn(1).setCellRenderer(leftRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginHistoryTable = new components.LoginHistory.LoginHistoryTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Login History");

        jScrollPane1.setBorder(null);

        loginHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User Name", "Full Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(loginHistoryTable);
        if (loginHistoryTable.getColumnModel().getColumnCount() > 0) {
            loginHistoryTable.getColumnModel().getColumn(0).setMinWidth(200);
            loginHistoryTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            loginHistoryTable.getColumnModel().getColumn(0).setMaxWidth(200);
            loginHistoryTable.getColumnModel().getColumn(2).setMinWidth(200);
            loginHistoryTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            loginHistoryTable.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(766, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private components.LoginHistory.LoginHistoryTable loginHistoryTable;
    // End of variables declaration//GEN-END:variables
}
