/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.userManager.ListFriend;

import Interface.Friend;
import Interface.User;
import com.google.gson.Gson;
import components.userManager.LoginHistory.*;
import components.GroupChatList.ViewAllMember.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import project.DataBase;

/**
 *
 * @author lnt09
 */
public class UserManagerListFriend extends javax.swing.JPanel {

    /**
     * Creates new form GroupChatListAllMember
     */
    private String username;

    private String id = null;

    public UserManagerListFriend(String id, String name) {
        this.id = id;
        initComponents();

        // Add fake data
        try {
            usernameText.setText(name);
        } catch (Exception err) {
            System.out.println("Loi trong khoi tao");
            err.printStackTrace();
        }
//        username = name;

        new CallAPIListFriend().execute();
    }

    private class CallAPIListFriend extends SwingWorker<String, Friend[]> {

        @Override
        protected String doInBackground() {
            try {
//                String api = "http://13.215.176.178:8881/admin/friend-list/" + id;
                String api = DataBase.serverUrl+"/admin/friend-list/" + id;

                HttpClient client = HttpClient.newHttpClient();
                HttpRequest req = HttpRequest.newBuilder()
                        .uri(new URI(api))
                        .GET()
                        .header("Content-Type", "application/json")
                        .build();

                HttpResponse<String> res = client.send(req, HttpResponse.BodyHandlers.ofString());

                int resCode = res.statusCode();
                String body = res.body();

                JSONParser par = new JSONParser();

                if (resCode == 200) {

                    JSONArray data = (JSONArray) par.parse(body);
                    String json = data.toString();

                    Gson gson = new Gson();
                    Friend[] list = gson.fromJson(json, Friend[].class);

                    publish(list);

                    return "Done";
                } else {
                    JSONObject err = (JSONObject) par.parse(body);
                    JOptionPane.showMessageDialog(null, String.valueOf(err.get("error")), "ERROR", JOptionPane.ERROR_MESSAGE);

                    return "Failed";
                }
            } catch (IOException ex) {
                Logger.getLogger(UserManagerListFriend.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(UserManagerListFriend.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(UserManagerListFriend.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(UserManagerListFriend.class.getName()).log(Level.SEVERE, null, ex);
            }
            return "failed";
        }

        @Override
        protected void process(List<Friend[]> chunks) {
            Friend[] data = chunks.get(chunks.size() - 1);

            userManagerListFriendTable.clearData();
            for (Friend user : data) {
                userManagerListFriendTable.addFriendRow(user);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousPageUserManager = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userManagerListFriendTable = new components.userManager.ListFriend.UserManagerListFriendTable();

        setBackground(new java.awt.Color(255, 255, 255));

        previousPageUserManager.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        previousPageUserManager.setForeground(new java.awt.Color(127, 127, 127));
        previousPageUserManager.setText("User Manager");
        previousPageUserManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("/ List friend of");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));

        usernameText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        usernameText.setForeground(new java.awt.Color(51, 51, 51));

        jScrollPane2.setBorder(null);

        userManagerListFriendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Full Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userManagerListFriendTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousPageUserManager)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previousPageUserManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    public void addListenerPreviousPageUserManager(MouseAdapter e) {
        previousPageUserManager.addMouseListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel previousPageUserManager;
    private components.userManager.ListFriend.UserManagerListFriendTable userManagerListFriendTable;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
