package components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogoAndTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelOption = new javax.swing.JPanel();
        userManagerOption = new javax.swing.JLabel();
        spamAndReportOption = new javax.swing.JLabel();
        loginHistoryOption = new javax.swing.JLabel();
        groupChatListOption = new javax.swing.JLabel();
        newRegisteredOption = new javax.swing.JLabel();
        registeredChartOption1 = new javax.swing.JLabel();
        userRelatedOption1 = new javax.swing.JLabel();
        userOnlineOption = new javax.swing.JLabel();
        userOnlineChartOption = new javax.swing.JLabel();

        panelLogoAndTitle.setForeground(new java.awt.Color(255, 255, 255));
        panelLogoAndTitle.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/logo.png"))); // NOI18N
        jLabel2.setText("Adminstrator");

        javax.swing.GroupLayout panelLogoAndTitleLayout = new javax.swing.GroupLayout(panelLogoAndTitle);
        panelLogoAndTitle.setLayout(panelLogoAndTitleLayout);
        panelLogoAndTitleLayout.setHorizontalGroup(
            panelLogoAndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );
        panelLogoAndTitleLayout.setVerticalGroup(
            panelLogoAndTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoAndTitleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOption.setOpaque(false);

        userManagerOption.setBackground(new java.awt.Color(130, 159, 239));
        userManagerOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userManagerOption.setForeground(new java.awt.Color(255, 255, 255));
        userManagerOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userManagerOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/8.png"))); // NOI18N
        userManagerOption.setText("User Manager");
        userManagerOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManagerOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManagerOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userManagerOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userManagerOptionMouseExited(evt);
            }
        });

        spamAndReportOption.setBackground(new java.awt.Color(130, 159, 239));
        spamAndReportOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        spamAndReportOption.setForeground(new java.awt.Color(255, 255, 255));
        spamAndReportOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spamAndReportOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/flag.png"))); // NOI18N
        spamAndReportOption.setText("Spam and Report");
        spamAndReportOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spamAndReportOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spamAndReportOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spamAndReportOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spamAndReportOptionMouseExited(evt);
            }
        });

        loginHistoryOption.setBackground(new java.awt.Color(130, 159, 239));
        loginHistoryOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginHistoryOption.setForeground(new java.awt.Color(255, 255, 255));
        loginHistoryOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHistoryOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/2.png"))); // NOI18N
        loginHistoryOption.setText("Login History");
        loginHistoryOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginHistoryOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHistoryOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginHistoryOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginHistoryOptionMouseExited(evt);
            }
        });

        groupChatListOption.setBackground(new java.awt.Color(130, 159, 239));
        groupChatListOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupChatListOption.setForeground(new java.awt.Color(255, 255, 255));
        groupChatListOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupChatListOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/5.png"))); // NOI18N
        groupChatListOption.setText("Group Chat List");
        groupChatListOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groupChatListOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupChatListOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                groupChatListOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupChatListOptionMouseExited(evt);
            }
        });

        newRegisteredOption.setBackground(new java.awt.Color(130, 159, 239));
        newRegisteredOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        newRegisteredOption.setForeground(new java.awt.Color(255, 255, 255));
        newRegisteredOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newRegisteredOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/7.png"))); // NOI18N
        newRegisteredOption.setText("New Registered");
        newRegisteredOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newRegisteredOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newRegisteredOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newRegisteredOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newRegisteredOptionMouseExited(evt);
            }
        });

        registeredChartOption1.setBackground(new java.awt.Color(130, 159, 239));
        registeredChartOption1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registeredChartOption1.setForeground(new java.awt.Color(255, 255, 255));
        registeredChartOption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registeredChartOption1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/stock.png"))); // NOI18N
        registeredChartOption1.setText("Registered Chart");
        registeredChartOption1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registeredChartOption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registeredChartOption1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registeredChartOption1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registeredChartOption1MouseExited(evt);
            }
        });

        userRelatedOption1.setBackground(new java.awt.Color(130, 159, 239));
        userRelatedOption1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userRelatedOption1.setForeground(new java.awt.Color(255, 255, 255));
        userRelatedOption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRelatedOption1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/3.png"))); // NOI18N
        userRelatedOption1.setText("User Related");
        userRelatedOption1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userRelatedOption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRelatedOption1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userRelatedOption1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userRelatedOption1MouseExited(evt);
            }
        });

        userOnlineOption.setBackground(new java.awt.Color(130, 159, 239));
        userOnlineOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userOnlineOption.setForeground(new java.awt.Color(255, 255, 255));
        userOnlineOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userOnlineOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/4.png"))); // NOI18N
        userOnlineOption.setText("User Online");
        userOnlineOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userOnlineOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userOnlineOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userOnlineOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userOnlineOptionMouseExited(evt);
            }
        });

        userOnlineChartOption.setBackground(new java.awt.Color(130, 159, 239));
        userOnlineChartOption.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userOnlineChartOption.setForeground(new java.awt.Color(255, 255, 255));
        userOnlineChartOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userOnlineChartOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/1.png"))); // NOI18N
        userOnlineChartOption.setText("User Online Chart");
        userOnlineChartOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userOnlineChartOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userOnlineChartOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userOnlineChartOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userOnlineChartOptionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOptionLayout = new javax.swing.GroupLayout(panelOption);
        panelOption.setLayout(panelOptionLayout);
        panelOptionLayout.setHorizontalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagerOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginHistoryOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spamAndReportOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupChatListOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newRegisteredOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registeredChartOption1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userRelatedOption1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userOnlineOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userOnlineChartOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOptionLayout.setVerticalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOptionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(userManagerOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginHistoryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupChatListOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spamAndReportOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newRegisteredOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registeredChartOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userRelatedOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userOnlineOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userOnlineChartOption, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogoAndTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogoAndTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userManagerOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagerOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userManagerOptionMouseClicked

    private void spamAndReportOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spamAndReportOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spamAndReportOptionMouseClicked

    private void loginHistoryOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginHistoryOptionMouseClicked

    private void groupChatListOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupChatListOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_groupChatListOptionMouseClicked

    private void userOnlineChartOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineChartOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userOnlineChartOptionMouseClicked

    private void newRegisteredOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newRegisteredOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newRegisteredOptionMouseClicked

    private void registeredChartOption1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredChartOption1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredChartOption1MouseClicked

    private void userRelatedOption1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRelatedOption1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userRelatedOption1MouseClicked

    private void userOnlineOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userOnlineOptionMouseClicked

    private void userManagerOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagerOptionMouseEntered
        userManagerOption.setOpaque(true);
        userManagerOption.setBackground(new Color(130, 159, 239));
        userManagerOption.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_userManagerOptionMouseEntered

    private void loginHistoryOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryOptionMouseEntered
        loginHistoryOption.setOpaque(true);
        loginHistoryOption.setBackground(new Color(130, 159, 239));
        loginHistoryOption.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_loginHistoryOptionMouseEntered

    private void userManagerOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManagerOptionMouseExited
        // TODO add your handling code here:
        userManagerOption.setOpaque(false);
        userManagerOption.setBackground(null);

    }//GEN-LAST:event_userManagerOptionMouseExited

    private void loginHistoryOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHistoryOptionMouseExited
        // TODO add your handling code here:
        loginHistoryOption.setOpaque(false);
        loginHistoryOption.setBackground(null);
    }//GEN-LAST:event_loginHistoryOptionMouseExited

    private void groupChatListOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupChatListOptionMouseEntered
        // TODO add your handling code here:
        groupChatListOption.setOpaque(true);
        groupChatListOption.setBackground(new Color(130, 159, 239));
        groupChatListOption.repaint();
    }//GEN-LAST:event_groupChatListOptionMouseEntered

    private void groupChatListOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupChatListOptionMouseExited
        groupChatListOption.setOpaque(false);
        groupChatListOption.setBackground(null);

    }//GEN-LAST:event_groupChatListOptionMouseExited

    private void spamAndReportOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spamAndReportOptionMouseEntered
        // TODO add your handling code here:
        spamAndReportOption.setOpaque(true);
        spamAndReportOption.setBackground(new Color(130, 159, 239));
        spamAndReportOption.repaint();

    }//GEN-LAST:event_spamAndReportOptionMouseEntered

    private void spamAndReportOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spamAndReportOptionMouseExited
        // TODO add your handling code here:
        spamAndReportOption.setOpaque(false);
        spamAndReportOption.setBackground(null);

    }//GEN-LAST:event_spamAndReportOptionMouseExited

    private void newRegisteredOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newRegisteredOptionMouseEntered
        // TODO add your handling code here:
        newRegisteredOption.setOpaque(true);
        newRegisteredOption.setBackground(new Color(130, 159, 239));
        newRegisteredOption.repaint();
    }//GEN-LAST:event_newRegisteredOptionMouseEntered

    private void newRegisteredOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newRegisteredOptionMouseExited
        // TODO add your handling code here:
        newRegisteredOption.setOpaque(false);
        newRegisteredOption.setBackground(null);

    }//GEN-LAST:event_newRegisteredOptionMouseExited

    private void registeredChartOption1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredChartOption1MouseEntered

        registeredChartOption1.setOpaque(true);
        registeredChartOption1.setBackground(new Color(130, 159, 239));
        registeredChartOption1.repaint();
    }//GEN-LAST:event_registeredChartOption1MouseEntered

    private void registeredChartOption1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredChartOption1MouseExited
        // TODO add your handling code here:
        registeredChartOption1.setOpaque(false);
        registeredChartOption1.setBackground(null);
    }//GEN-LAST:event_registeredChartOption1MouseExited

    private void userRelatedOption1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRelatedOption1MouseEntered
        // TODO add your handling code here:

        userRelatedOption1.setOpaque(true);
        userRelatedOption1.setBackground(new Color(130, 159, 239));
        userRelatedOption1.repaint();

    }//GEN-LAST:event_userRelatedOption1MouseEntered

    private void userRelatedOption1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRelatedOption1MouseExited
        userRelatedOption1.setOpaque(false);
        userRelatedOption1.setBackground(null);

    }//GEN-LAST:event_userRelatedOption1MouseExited

    private void userOnlineOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineOptionMouseEntered
        // TODO add your handling code here:
        userOnlineOption.setOpaque(true);
        userOnlineOption.setBackground(new Color(130, 159, 239));
        userOnlineOption.repaint();

    }//GEN-LAST:event_userOnlineOptionMouseEntered

    private void userOnlineOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineOptionMouseExited
        // TODO add your handling code here:
        userOnlineOption.setOpaque(false);
        userOnlineOption.setBackground(null);

    }//GEN-LAST:event_userOnlineOptionMouseExited

    private void userOnlineChartOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineChartOptionMouseEntered
        // TODO add your handling code here:
        userOnlineChartOption.setOpaque(true);
        userOnlineChartOption.setBackground(new Color(130, 159, 239));
        userOnlineChartOption.repaint();
    }//GEN-LAST:event_userOnlineChartOptionMouseEntered

    private void userOnlineChartOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOnlineChartOptionMouseExited
        // TODO add your handling code here:
        userOnlineChartOption.setOpaque(false);
        userOnlineChartOption.setBackground(null);
    }//GEN-LAST:event_userOnlineChartOptionMouseExited

    // ----------------------------------------------------
    //          Add Listener
    // ----------------------------------------------------
    public void addListenerUserManager(MouseAdapter listener) {
        userManagerOption.addMouseListener(listener);
    }

    public void addListenerLoginHistory(MouseAdapter listener) {
        loginHistoryOption.addMouseListener(listener);
    }

    public void addListenerGroupChatList(MouseAdapter listener) {
        groupChatListOption.addMouseListener(listener);
    }

    public void addListenerSpamAndReportOption(MouseAdapter listener) {
        spamAndReportOption.addMouseListener(listener);
    }
    public void addListenerNewRegisteredOption(MouseAdapter listener){
        newRegisteredOption.addMouseListener(listener);
        
    }
    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#4286f4"), 0, getHeight(), Color.decode("#373B44"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    private int x;
    private int y;

    public void initMoving(JFrame fram) {
        panelLogoAndTitle.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }
        });
        panelLogoAndTitle.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                fram.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupChatListOption;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loginHistoryOption;
    private javax.swing.JLabel newRegisteredOption;
    private javax.swing.JPanel panelLogoAndTitle;
    private javax.swing.JPanel panelOption;
    private javax.swing.JLabel registeredChartOption1;
    private javax.swing.JLabel spamAndReportOption;
    private javax.swing.JLabel userManagerOption;
    private javax.swing.JLabel userOnlineChartOption;
    private javax.swing.JLabel userOnlineOption;
    private javax.swing.JLabel userRelatedOption1;
    // End of variables declaration//GEN-END:variables
}
