/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import components.GroupChatList.GroupChatList;
import components.GroupChatList.ViewAllAdmin.GroupChatListAllAdmin;
import components.GroupChatList.ViewAllMember.GroupChatListAllMember;
import components.LoginHistory.LoginHistory;
import components.NewRegistered.NewRegistered;
import components.RegisteredChart.FormRegisteredChart;
import components.SpamAndReport.SpamAndReport;
import components.UserOnline.UserOnline;
import components.UserOnlineChart.FormUserOnlineChart;
import components.UserRelated.UserRelated;
import components.userManager.ListFriend.UserManagerListFriend;
import components.userManager.LoginHistory.UserManagerLoginHistory;
import java.awt.Color;
import javax.swing.JComponent;
import components.userManager.UserManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import project.AdminLogin;
import project.DashBoardMain;

/**
 *
 * @author lnt09
 */
public class Main extends javax.swing.JFrame {

    private AdminLogin loginView = null;
    private DashBoardMain dashBoardMainView = null;
    private String id;
    public Main() {
       initComponents();
       loginView = new AdminLogin();
       loginView.setVisible(true);
       loginView.addListenerButton(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e) {
               id = loginView.callAPI();
               if(id != null)
               {
                   System.out.println("id:"+id);
                   loginView.setVisible(false);
                   dashBoardMainView = new DashBoardMain(id);
                   dashBoardMainView.setVisible(true);
               }
           }
       });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new project.PanelBorder();

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Main();   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private project.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
