/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components.GroupChatList.ViewAllMember;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author lnt09
 */
public class GroupChatListAllMember extends javax.swing.JPanel {

    /**
     * Creates new form GroupChatListAllMember
     */
    private String groupName;

    public GroupChatListAllMember(String name) {
        initComponents();

        // Add fake data
        for (int i = 0; i < 50; i++) {
            groupChatListAllMemberTable.addRow(new Object[]{"lenguyenthai123", "Lê Nguyên Thái", "Member", "2023/12/6"});
            groupChatListAllMemberTable.addRow(new Object[]{"lenguyenthai123", "Lê Nguyên Thái", "Admin", "2023/12/6"});
        }

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        groupChatListAllMemberTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        groupNameText.setText(name);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previousPageGroupChat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupChatListAllMemberTable = new components.GroupChatList.ViewAllMember.GroupChatListAllMemberTable();
        jLabel2 = new javax.swing.JLabel();
        groupNameText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        previousPageGroupChat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        previousPageGroupChat.setForeground(new java.awt.Color(127, 127, 127));
        previousPageGroupChat.setText("Group Chat");
        previousPageGroupChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("/ Member List of");

        jScrollPane1.setBorder(null);

        groupChatListAllMemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Full Name", "Role", "Participate Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(groupChatListAllMemberTable);
        if (groupChatListAllMemberTable.getColumnModel().getColumnCount() > 0) {
            groupChatListAllMemberTable.getColumnModel().getColumn(0).setMinWidth(250);
            groupChatListAllMemberTable.getColumnModel().getColumn(0).setPreferredWidth(250);
            groupChatListAllMemberTable.getColumnModel().getColumn(0).setMaxWidth(250);
            groupChatListAllMemberTable.getColumnModel().getColumn(1).setMinWidth(250);
            groupChatListAllMemberTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            groupChatListAllMemberTable.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));

        groupNameText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        groupNameText.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousPageGroupChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousPageGroupChat)
                    .addComponent(jLabel1)
                    .addComponent(groupNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    public void addListenerPreviousPageGroupChat(MouseAdapter e) {
        previousPageGroupChat.addMouseListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.GroupChatList.ViewAllMember.GroupChatListAllMemberTable groupChatListAllMemberTable;
    private javax.swing.JLabel groupNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel previousPageGroupChat;
    // End of variables declaration//GEN-END:variables
}
